### ISSUE TITLE
ShedLock does not work with PostgreSQL JDBC Driver version 42.2.11

### ISSUE THREAD

**Issue by kerdotnet** [lukas-krecan/ShedLock#207] opened 2020-03-19 14:49 UTC
1. Which version do you use
shedlock-spring:4.5.1
2. Which Lock Provider
shedlock-provider-jdbc-template:4.5.1
3. ShedLock configuration 
lockAtLeastFor = "PT10S",
lockAtMostFor = "PT120S"

**Expected behavior**
Shedlock can start without errors

**Actual behavior**
After an update on the latest PostgreSQL JDBC Driver JDBC 4.2 » 42.2.11 and deployment we found that Shedlock can not start because of error:
```
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is org.postgresql.util.PSQLException: The database returned ROLLBACK, so the transaction cannot be committed. Transaction failure cause is <<ERROR: duplicate key value violates unique constraint "shedlock_pkey"
  Detail: Key (name)=(documentProcessingJob) already exists.>>
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:334)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744) 
```

**Comment by lukas-krecan** [comment] 2020-03-20 07:04
Thanks for reporting, it's indeed the case. Will take a look at it.

**Comment by lukas-krecan** [comment] 2020-03-20 07:12
Caused by https://github.com/pgjdbc/pgjdbc/pull/1729

**Comment by lukas-krecan** [comment] 2020-03-20 07:14
Can be fixed by setting `raiseExceptionOnSilentRollback=false` connection property. Frankly, I think it's a bug in Postgres SQL driver and I will wait before considering implementing a workaround.

**Comment by kerdotnet** [comment] 2020-03-20 07:35
Thanks for the information!

**Comment by davecramer** [comment] 2020-03-20 14:50
This is NOT. bug in the driver. This was done on purpose as the SQL Standard requires that errors be thrown if the transaction cannot be committed

**Comment by lukas-krecan** [comment] 2020-03-20 19:25
Fixed in 4.5.2

**Closed by lukas-krecan** 2020-03-20 19:25 UTC

**Comment by pavel-is24** [comment] 2020-04-03 11:11
I am just join to leave some keywords here for someone googling this issue in future:

ShedLock, Spring boot upgrade, PostgreSQL.

We have upgraded Sprint Boot from v2.1 to v2.2 and got

```
Detail: Key (name)=(myclass_mymethod) already exists.>>
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:335)
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "shedlock_pkey"
  Detail: Key (name)=(myclass_mymethod) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
...
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
```

**Comment by davecramer** [comment] 2020-04-03 11:14
FWIW PgJDBC 42.2.12 has been released and this change has been reverted. We (the PgJDBC group are recommending that 42.2.11 not be used and use 42.2.12 instead.
Also note that we will be releasing 42.3.0 with the above mentioned change.
