### ISSUE TITLE
when RedisLockProvider.lock invoke sometimes throw NullException

### ISSUE THREAD

**Issue by rc452860** [lukas-krecan/ShedLock#178] opened 2019-12-12 06:06 UTC
I replace default redis client to redisson,and get NullException.

**Describe the bug**
1. Which version do you use
3.0.0
2. Which Lock Provider
shedlock-provider-redis-spring
3. ShedLock configuration

4. ShedLock logs

**Expected behavior**
![image](https://user-images.githubusercontent.com/3949222/70686822-6292ce00-1ce8-11ea-99ff-71f367d86e84.png)
![image](https://user-images.githubusercontent.com/3949222/70686834-6b839f80-1ce8-11ea-9e46-aae67860b589.png)

**Actual behavior**
No exception.

**Comment by lukas-krecan** [comment] 2019-12-13 07:54
Thanks for the report. It seems that Redis template may indeed return null. I will fix the code to take it in the account.

**Comment by lukas-krecan** [comment] 2019-12-13 12:13
It may be caused by redis pipelines or transactions. Could you please share your RedisConnectionFactory config?

**Comment by lukas-krecan** [comment] 2019-12-14 08:29
It seems that it's a bug in Redisson. It returns null when set operation was not successful (it should return false). I have a workaround in ShedLock and I will report an issue in Redisson.

**Comment by lukas-krecan** [comment] 2019-12-14 16:01
Released as 4.0.2

**Closed by lukas-krecan** 2019-12-14 16:01 UTC

**Comment by rc452860** [comment] 2019-12-26 02:31
sorry,China's network is not very good recently.I can's use proxy to access gmail. can't recive mail notification. glad you alread resloved this problem.
